before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libaspell-dev aspell aspell-en
language: ruby
rvm:
  - 2.1.0
script:
  - rspec spec
  - ruby run_skeptic.rb skeptic.yml engine/
